### ISSUE TITLE
how to work with only 1 gpu.?

### ISSUE THREAD

**Issue by ramnamaqsood776** [leftthomas/SquashCapsuleNet#2]
Hello
Could you please guide me about the pre-trained model you used in your train file and can we run this code on only 1 gpu ? if yes, then how it is possible to use pre-trained model on 1 gpu only as whenever i change code according to my gpu it gives me error 

> **RecursionError: maximum recursion depth exceeded while calling a Python object**

**Comment by leftthomas** [comment]
@ramnamaqsood776 you should change code, this is a PyTorch question, you can reference the document of PyTorch
