### ISSUE TITLE
Where can I find the model with kinetics600_r2plus1d.pth?

### ISSUE THREAD

**Issue by Weed-eat-meat** [leftthomas/SquashCapsuleNet#3]
Hi! I want to retrain the network with one other dataset, but don't have kinetics600_r2plus1d.pth. I want to know where to find the model?

**Comment by leftthomas** [comment]
@Weed-eat-meat read `readme` carefully, **Because the training time is too long, so this experiment have not been finished.**

**Comment by Weed-eat-meat** [comment]
So are you training from scratch in ucf101 and HMDB51? And your experiments still have some differents with the original author?

**Comment by leftthomas** [comment]
@Weed-eat-meat I have trained from scratch in these two datasets. Some implementation details maybe different from the original paper, I just reimplement the paper as I understand.

**Comment by Weed-eat-meat** [comment]
oh, oh, thank you.

**Comment by huamgmin** [comment]
hi,l know you haven't finished the train in kinetics600_r2plus1d,
but have you saved the model that trained 350 hours, can you send it to me? 
l want to continue train it ,if finished i will share it.
my qq :2458237010

**Comment by Weed-eat-meat** [comment]
sorry，i don't do this work.



At 2020-05-20 13:20:05, "huamgmin" <notifications@github.com> wrote:

hi,l know you haven't finished the train in kinetics600_r2plus1d,
but have you saved the model that trained 350 hours, can you send it to me?
l want to continue train it ,if finished i will share it.
my qq :2458237010
