### ISSUE TITLE
Something about R2Pluse1D_model trained on Kinetics600

### ISSUE THREAD

**Issue by huamgmin** [leftthomas/SquashCapsuleNet#4]
Hi,
l know you haven't finished the  R2Pluse1D_model train on Kinetics600,
BUT have you saved the parameters model that trained 350 hours,
l want to continue train this model, if l finished it ,i'll share it to you .
THANKS!
qq: 2458237010

**Comment by huamgmin** [comment]
And  emmm, 
FIRST ,I don't know whether what i think is right,
i find in R2Plus1D.py that when we choose the first_conv =False,
you operate BN and RELU after conv, but in  CLASS---SpatioTemporalResBlock, you do it again, which i think is wrong.  
AND i am such a new hand in DL,so if i was wrong ,please tell me!!!
THANK YOU VERY MUCH !!

**Comment by daihu-ye** [comment]
Hi, huamgmin. Have you done training the model and got the results?

**Comment by huamgmin** [comment]
l've got 60% on HMDB51 and 93% on ucf101。

**Comment by huamgmin** [comment]
I've got 60% on HMDB51 and 93% on UCF101
