### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by Heroism502** [leftthomas/SquashCapsuleNet#6]
请问怎么解决这个问题：
![image](https://user-images.githubusercontent.com/22213368/140633828-a2b4ef0e-3a42-484c-ac86-f3efecdea902.png)

**Comment by Heroism502** [comment]
请问能告知下怎么解决吗

**Comment by leftthomas** [comment]
@xieliang11111 , you should learn how to debug by yourself.
